# Generated by Django 3.2.11 on 2022-05-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='titulo',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
