# Generated by Django 3.2.11 on 2022-05-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen_banner',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
