# Generated by Django 3.2.11 on 2022-05-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_imagen_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen_banner',
            field=models.URLField(blank=True, null=True),
        ),
    ]
