# Generated by Django 3.2.11 on 2022-05-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='apodo',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
