# Generated by Django 3.2.11 on 2022-05-05 16:57

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_post_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='biografia',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
